import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

const aiOptions = {
  apiKey: process.env.GEMINI_API_KEY || "",
};

// Only initialize if we have a key
const ai = aiOptions.apiKey ? new GoogleGenAI(aiOptions) : null;

// The "System Prompt" (Context/Persona)
const SYSTEM_PROMPT = `You are a world-class, elite MetaQuotes Language 5 (MQL5) developer and quantitative algorithmic trader. 
You specialize in writing flawless, highly profitable, and cleanly structured Expert Advisors (EAs) and Custom Indicators for MetaTrader 5.

CRITICAL RULES:
1. ONLY output valid, exact MQL5 code.
2. Put the code inside a markdown block: \`\`\`mql5 ...code... \`\`\`
3. Do NOT include explanations, "Here is the code", or any natural language outside the code block.
4. The code MUST compile without errors or warnings in MetaEditor 5.
5. Include standard includes like <Trade\\Trade.mqh>.
6. Always implement solid Risk Management (Stop Loss, Take Profit, trailing stops, or explicit lot sizing) as inputs.
7. Always include descriptive #property comments and clean code separating OnInit, OnDeinit, and OnTick.
8. If the user's strategy is vague, infer the best standard technical trading practices to make a complete, functioning EA.`;

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    if (!ai) {
      // FALLBACK / MOCK (If no API key is provided)
      await new Promise((resolve) => setTimeout(resolve, 2000));
      const mockCode = `//+------------------------------------------------------------------+
//|                                                   AI_Generated.mq5 |
//|                                     Please Set GEMINI_API_KEY in   |
//|                                     your .env.local file to use AI |
//+------------------------------------------------------------------+
#property copyright "Generated by MQL5.ai (Demo Mode)"
#property link      "https://mql5.ai"
#property version   "1.00"

#include <Trade\\Trade.mqh>
CTrade trade;

//--- Input Parameters
input double InpLotSize = 0.1;           // Lot Size

int OnInit() {
   Print("AI Bot Demo Initialized.");
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason) {
   Print("Bot Demo Stopped.");
}

void OnTick() {
   // Waiting for real AI generation (API Key missing)
}`;
      return NextResponse.json({ code: mockCode });
    }

    // REAL AI GENERATION (Gemini 3.1)
    // REAL AI GENERATION
    // The gemini api expects generateContent to be called on a model instance or with model specified
    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: [
        { role: "user", parts: [{ text: prompt }] },
      ],
      config: {
        systemInstruction: SYSTEM_PROMPT,
        temperature: 0.2, // Low temperature for coding precision
      }
    });

    if (response.text) {
      const text = response.text;
      // Extract code block
      const mql5Match = text.match(/```(?:mql5|mql|c\+\+)?([\s\S]*?)```/);

      if (mql5Match) {
        return NextResponse.json({ code: mql5Match[1].trim() });
      }

      // If the AI forgot the markdown block but returned code anyway
      return NextResponse.json({ code: text.trim() });
    } else {
      throw new Error("Empty response from AI");
    }

  } catch (error: any) {
    console.error("AI API Error:", error);

    // Provide a mocked response on API Rate Limit / Quota Exceeded
    const isRateLimit = String(error).includes("429") || String(error).includes("quota") || String(error).includes("RESOURCE_EXHAUSTED");

    if (isRateLimit) {
      const mockCode = `//+------------------------------------------------------------------+
//|                                             Advanced_TrendRev_EA.mq5 |
//|                                          Generated by MQL5.ai (Core) |
//|                                         (Quota Exceeded - DEMO MODE) |
//+------------------------------------------------------------------+
#property copyright "MQL5.ai Premium Strategy"
#property link      "https://mql5.ai"
#property version   "2.10"
#property description "Advanced Mean Reversion with Bollinger Bands & RSI"

#include <Trade\\Trade.mqh>

CTrade trade;

//--- Input Parameters
input group "=== Risk Management ==="
input double InpLotSize     = 0.1;       // Base Lot Size
input double InpMaxRiskPct  = 2.0;       // Max Risk per Trade (%)
input int    InpStopLoss    = 600;       // Stop Loss (Points)
input int    InpTakeProfit  = 1200;      // Take Profit (Points)
input bool   InpUseTrailing = true;      // Use Trailing Stop?
input int    InpTrailingAmt = 300;       // Trailing Stop Distance

input group "=== Bollinger Bands ==="
input int    InpBBPeriod    = 20;        // Bollinger Period
input double InpBBDev       = 2.0;       // Bollinger Deviations
input ENUM_APPLIED_PRICE InpBBPrice = PRICE_CLOSE;

input group "=== RSI Filter ==="
input int    InpRSIPeriod   = 14;        // RSI Period
input int    InpRSILower    = 30;        // RSI Oversold Level
input int    InpRSIUpper    = 70;        // RSI Overbought Level

input group "=== General settings ==="
input ulong  InpMagicNumber = 888888;    // Magic Number

//--- Global Variables
int    bbHandle;
int    rsiHandle;
double bbUpperBuffer[];
double bbLowerBuffer[];
double rsiBuffer[];
double prices[];

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   // Initialize Indicators
   bbHandle = iBands(_Symbol, _Period, InpBBPeriod, 0, InpBBDev, InpBBPrice);
   rsiHandle = iRSI(_Symbol, _Period, InpRSIPeriod, PRICE_CLOSE);
   
   if(bbHandle == INVALID_HANDLE || rsiHandle == INVALID_HANDLE)
     {
      Print("Error creating indicator handles");
      return(INIT_FAILED);
     }
     
   ArraySetAsSeries(bbUpperBuffer, true);
   ArraySetAsSeries(bbLowerBuffer, true);
   ArraySetAsSeries(rsiBuffer, true);
   ArraySetAsSeries(prices, true);
   
   Print("Advanced TrendRev EA Initialized Successfully.");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   IndicatorRelease(bbHandle);
   IndicatorRelease(rsiHandle);
   Print("Advanced TrendRev EA Stopped.");
  }

//+------------------------------------------------------------------+
//| Trailing Stop Logic                                              |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(!InpUseTrailing) return;
   
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   
   for(int i = PositionsTotal()-1; i>=0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
         double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
         double currentSL = PositionGetDouble(POSITION_SL);
         long   posType   = PositionGetInteger(POSITION_TYPE);
         
         if(posType == POSITION_TYPE_BUY)
           {
            double newSL = bid - (InpTrailingAmt * point);
            if(newSL > currentSL && bid - openPrice > (InpTrailingAmt * point))
              {
               trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
              }
           }
         else if(posType == POSITION_TYPE_SELL)
           {
            double newSL = ask + (InpTrailingAmt * point);
            if((newSL < currentSL || currentSL == 0) && openPrice - ask > (InpTrailingAmt * point))
              {
               trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Dynamic Lot Sizing Logic                                         |
//+------------------------------------------------------------------+
double CalculateLotSize()
  {
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * (InpMaxRiskPct / 100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   
   if(tickValue > 0 && InpStopLoss > 0)
     {
      double calculatedLot = riskAmount / (InpStopLoss * tickValue);
      // Ensure lot is within symbol limits
      double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
      double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
      return MathMax(minLot, MathMin(maxLot, NormalizeDouble(calculatedLot, 2)));
     }
   
   return InpLotSize; // Fallback
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   ManageTrailingStop();
  
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, _Period, 0);
   if(lastBarTime == currentBarTime) return; // Process only on new bar close

   if(CopyBuffer(bbHandle, UPPER_BAND, 1, 2, bbUpperBuffer) <= 0) return;
   if(CopyBuffer(bbHandle, LOWER_BAND, 1, 2, bbLowerBuffer) <= 0) return;
   if(CopyBuffer(rsiHandle, 0, 1, 2, rsiBuffer) <= 0) return;
   if(CopyClose(_Symbol, _Period, 1, 2, prices) <= 0) return;
   
   double currentPrice = prices[0];
   double currentRSI   = rsiBuffer[0];
   double bbUpper      = bbUpperBuffer[0];
   double bbLower      = bbLowerBuffer[0];
   
   bool isPositionOpen = PositionSelect(_Symbol);
   
   //================================================================
   // BUY CONDITION: Price hits lower BB AND RSI is Oversold (< 30)
   //================================================================
   if(currentPrice <= bbLower && currentRSI < InpRSILower)
     {
      if(isPositionOpen && PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL)
        {
         trade.PositionClose(_Symbol); // Close short position
        }
      
      if(!PositionSelect(_Symbol)) 
        {
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double sl = ask - InpStopLoss * _Point;
         double tp = ask + InpTakeProfit * _Point;
         double dynamicLot = CalculateLotSize();
         
         trade.Buy(dynamicLot, _Symbol, ask, sl, tp, "BB+RSI Buy Reversal");
         lastBarTime = currentBarTime;
        }
     }
     
   //================================================================
   // SELL CONDITION: Price hits upper BB AND RSI is Overbought (> 70)
   //================================================================
   else if(currentPrice >= bbUpper && currentRSI > InpRSIUpper)
     {
      if(isPositionOpen && PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
        {
         trade.PositionClose(_Symbol); // Close long position
        }
      
      if(!PositionSelect(_Symbol)) 
        {
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         double sl = bid + InpStopLoss * _Point;
         double tp = bid - InpTakeProfit * _Point;
         double dynamicLot = CalculateLotSize();
         
         trade.Sell(dynamicLot, _Symbol, bid, sl, tp, "BB+RSI Sell Reversal");
         lastBarTime = currentBarTime;
        }
     }
  }
//+------------------------------------------------------------------+`;
      return NextResponse.json({ code: mockCode });
    }

    return NextResponse.json({ error: "Failed to generate code.", details: String(error) }, { status: 500 });
  }
}
