"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Bot, Code2, Download, Loader2, Send, TerminalSquare } from "lucide-react";
import Link from "next/link";

export default function GeneratePage() {
    const [prompt, setPrompt] = useState("");
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedCode, setGeneratedCode] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!prompt.trim()) return;

        setIsGenerating(true);
        setGeneratedCode(null);

        try {
            // In the real app, this calls our API route
            const response = await fetch("/api/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ prompt }),
            });

            if (!response.ok) throw new Error("Failed to generate");

            const data = await response.json();
            setGeneratedCode(data.code);
        } catch (error) {
            console.error(error);
            // Fallback mock code for UI demonstration if API fails or is not yet implemented
            setTimeout(() => {
                setGeneratedCode(`//+------------------------------------------------------------------+
//|                                                 GeneratedBot.mq5 |
//|                                                Generated by AI   |
//+------------------------------------------------------------------+
#property copyright "MQL5.ai"
#property link      "https://mql5.ai"
#property version   "1.00"

#include <Trade\\Trade.mqh>
CTrade trade;

//--- input parameters
input double InpLotSize = 0.1;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   Print("Bot Initialized successfully.");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Your strategy logic goes here
   // This is a placeholder structure
  }
//+------------------------------------------------------------------+`);
            }, 3000);
        } finally {
            // We keep generating state true for mock if API fails until timeout finishes
            // But if API succeeds, we stop spinning
            if (generatedCode !== null) {
                setIsGenerating(false);
            }
        }
    };

    // Mock effect to clear loading state when fallback finishes
    // In a real scenario, the fetch handles it instantly
    useEffect(() => {
        if (generatedCode) setIsGenerating(false);
    }, [generatedCode]);

    const handleDownload = () => {
        if (!generatedCode) return;
        const blob = new Blob([generatedCode], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "GeneratedBot.mq5";
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="min-h-screen pt-24 pb-12 px-6">
            <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-8 h-[calc(100vh-140px)]">

                {/* Left Column: Input area */}
                <div className="flex flex-col h-full gap-4">
                    <Link href="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-white transition-colors w-fit mb-2">
                        <TerminalSquare className="w-5 h-5 text-primary" />
                        <span className="font-bold tracking-tight text-white">MQL5.ai</span>
                    </Link>

                    <div className="glass rounded-2xl p-6 flex-1 flex flex-col border border-white/5 relative overflow-hidden">
                        <h1 className="text-2xl font-bold mb-2">Describe your Strategy</h1>
                        <p className="text-gray-400 text-sm mb-6">
                            Be as specific as possible. Mention indicators, timeframes, risk management, and entry/exit conditions.
                        </p>

                        <textarea
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            placeholder="E.g. Create an Expert Advisor that buys when the 50 EMA crosses above the 200 EMA on the 1H timeframe. Set stop loss to 50 pips and take profit to 100 pips. Risk 1% per trade."
                            className="flex-1 w-full bg-surface/50 border border-white/10 rounded-xl p-4 text-white placeholder:text-gray-600 focus:outline-none focus:ring-2 focus:ring-primary/50 resize-none"
                            disabled={isGenerating}
                        />

                        <div className="mt-4 flex justify-between items-center">
                            <div className="text-xs text-gray-500 flex items-center gap-2">
                                <SparkleIcon className="w-4 h-4 text-accent" />
                                Uses GPT-4 Optimized for MQL5
                            </div>
                            <button
                                onClick={handleGenerate}
                                disabled={isGenerating || !prompt.trim()}
                                className="bg-primary text-white px-6 py-3 rounded-xl font-medium flex items-center gap-2 hover:bg-primary/90 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                {isGenerating ? (
                                    <>
                                        <Loader2 className="w-5 h-5 animate-spin" />
                                        Generating...
                                    </>
                                ) : (
                                    <>
                                        <Send className="w-5 h-5" />
                                        Build Bot
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </div>

                {/* Right Column: Code Viewer */}
                <div className="glass rounded-2xl border border-white/5 flex flex-col h-full overflow-hidden bg-[#0A0A0A]">
                    <div className="flex items-center justify-between px-4 py-3 border-b border-white/5 bg-black/40">
                        <div className="flex items-center gap-2 text-sm text-gray-400 font-mono">
                            <Code2 className="w-4 h-4" />
                            <span>{generatedCode ? "GeneratedBot.mq5" : "Output Terminal"}</span>
                        </div>
                        {generatedCode && (
                            <button
                                onClick={handleDownload}
                                className="text-xs flex items-center gap-2 bg-white/10 hover:bg-white/20 px-3 py-1.5 rounded-lg transition-colors text-white"
                            >
                                <Download className="w-3.5 h-3.5" />
                                Download .mq5
                            </button>
                        )}
                    </div>

                    <div className="flex-1 p-6 overflow-auto font-mono text-sm relative">
                        <AnimatePresence mode="wait">
                            {isGenerating ? (
                                <motion.div
                                    key="loading"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="absolute inset-0 flex flex-col items-center justify-center text-gray-500 gap-4"
                                >
                                    <Bot className="w-12 h-12 text-primary animate-pulse" />
                                    <div className="typewriter">
                                        <p>Analyzing strategy architecture...</p>
                                    </div>
                                </motion.div>
                            ) : generatedCode ? (
                                <motion.div
                                    key="code"
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    className="text-gray-300"
                                >
                                    <pre><code>{generatedCode}</code></pre>
                                </motion.div>
                            ) : (
                                <motion.div
                                    key="empty"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    className="absolute inset-0 flex items-center justify-center text-gray-600 flex-col gap-3"
                                >
                                    <TerminalSquare className="w-10 h-10 opacity-20" />
                                    <p>Your generated MQL5 code will appear here</p>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                </div>

            </div>
        </div>
    );
}

function SparkleIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
            <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z" />
        </svg>
    );
}
